name: daraz-tek
services:
  mattermost:
    image: mattermost/mattermost-team-edition:11.7@sha256:a9f01466ea96b559688fd67b07e6a1d381530a7888c74b87c4358869e5f1f06b
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost
    environment:
      TZ: Asia/Tokyo
      MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE: ja
      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes
      MM_SERVICESETTINGS_SITEURL: https://daraz-tek.beta.fogtype.com
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres?sslmode=disable&connect_timeout=10
      MM_TEAMSETTINGS_MAXUSERSPERTEAM: "100"
    depends_on:
      - postgres
  postgres:
    image: postgres:18-alpine@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD
  old_db:
    profiles:
      - migration
    image: postgres:17-alpine@sha256:979c4379dd698aba0b890599a6104e082035f98ef31d9b9291ec22f2b13059ca
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data_v17:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD
volumes:
  mattermost_data:
  postgres_data_v17:
  postgres_data:
