name: daraz-tek
services:
  reverse-proxy:
    image: alpine@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    restart: unless-stopped
    init: true
    command: sleep infinity
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.daraztek_reverse_proxy.rule: "Host(`daraz-tek.beta.fogtype.com`)"
      traefik.http.services.daraztek_reverse_proxy.loadbalancer.server.url: http://rho.fogtype.com:8065
networks:
  traefik:
    external: true
