name: daraz-tek
services:
  reverse-proxy:
    image: alpine@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    restart: unless-stopped
    init: true
    command: sleep infinity
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.daraztek_reverse_proxy.rule: "Host(`daraz-tek.beta.fogtype.com`)"
      traefik.http.services.daraztek_reverse_proxy.loadbalancer.server.url: http://rho.fogtype.com:8065
networks:
  traefik:
    external: true
