name: daraz-tek
services:
  mattermost:
    image: mattermost/mattermost-team-edition:11.8@sha256:ea589dabb1fce993381ae8fc2c74e06ae21e24575d843ec4c5903dd28ae3b909
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost
    environment:
      TZ: Asia/Tokyo
      MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE: ja
      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes
      MM_SERVICESETTINGS_SITEURL: https://daraz-tek.beta.fogtype.com
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres?sslmode=disable&connect_timeout=10
      MM_TEAMSETTINGS_MAXUSERSPERTEAM: "100"
    depends_on:
      - postgres
  postgres:
    image: postgres:18-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD
volumes:
  mattermost_data:
  postgres_data:
