name: daraz-tek
services:
  mattermost:
    image: mattermost/mattermost-team-edition:11.8@sha256:fba40ff3283798c3e67d680e51146d87e2af37449e5fe0f79a09aad23415c809
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost
    environment:
      TZ: Asia/Tokyo
      MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE: ja
      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes
      MM_SERVICESETTINGS_SITEURL: https://daraz-tek.beta.fogtype.com
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/postgres?sslmode=disable&connect_timeout=10
      MM_TEAMSETTINGS_MAXUSERSPERTEAM: "100"
    depends_on:
      - postgres
  postgres:
    image: postgres:18-alpine@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD
volumes:
  mattermost_data:
  postgres_data:
